name: Helm install

on:
  push:
    branches:
      - main
    paths:
      - chart/**

jobs:
  setup-helm:
    runs-on: ubuntu-latest
    name: Install Helm
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Get GKE Credentials' 
        id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'main-cluster'
          location: 'us-central1'

      - uses: azure/setup-helm@v4.2.0
        id: install